#Spring Boot 其默认是集成web容器的，Spring Boot将容器内置后，它通过配置文件的方式类修改相关server配置，感觉和部署的发布服务器没关系
server:
  port: 80
  context-path: /demo/

#  swagger开关, logger调试日志开关
demo:
  swagger-open: true
  logger-open: true


